# Generated by Django 4.1 on 2022-10-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Number2', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
